### ISSUE TITLE
have better exception thrown if container doesn't have the right method

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-transaction#15] opened 2016-03-28 00:08 UTC
```
container = {
  process: -> input { input.each { |row| row[:name] = row.delete(:sku_name) } }
}

transaction = Dry.Transaction(container: container) do
  map :process
  tee :map
end

transaction.([{sku_name: 'hi'}])
```

results in: 

```
/usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/dry-transaction-0.5.0/lib/dry/transaction/step_adapters/base.rb:15:in `method': undefined method `call' for class `NilClass' (NameError)
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/dry-transaction-0.5.0/lib/dry/transaction/step_adapters/base.rb:15:in `arity'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/dry-transaction-0.5.0/lib/dry/transaction/step.rb:38:in `arity'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/dry-transaction-0.5.0/lib/dry/transaction/sequence.rb:268:in `block in assert_options_satisfy_step_arity'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/dry-transaction-0.5.0/lib/dry/transaction/sequence.rb:267:in `each'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/dry-transaction-0.5.0/lib/dry/transaction/sequence.rb:267:in `assert_options_satisfy_step_arity'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/dry-transaction-0.5.0/lib/dry/transaction/sequence.rb:45:in `call'
    from csv_converter.rb:32:in `<main>'
```

Would like to see something like "container doesn't have method 'map' defined" or whatever.

**Comment by timriley** [comment] 2016-03-29 00:10
Thanks for the report, @joevandyk!

I actually think this is an issue more with our documentation than our implementation of resolving items from the container. The problem is that our docs use a hash, which doesn't offer the most ideal container-like behaviour.

For example, if I set up a Dry::Container and fetch a non-existent item, I get a much better error:

``` ruby
MyContainer = Class.new do
  extend Dry::Container::Mixin
end

MyContainer[:missing]
# => Dry::Container::Error: Nothing registered with the key :foo
```

This is a much nicer error and also better-located: it should really be the container's job to tell us if something is missing.

To address this, I think I'll shift the documentation to use dry-container rather than a hash, which will make it clear that dry-transaction is best used with a proper container implementation. I'll ping you once I've done that :) Thanks again for looking into all of this!

**Closed as completed by timriley** 2016-03-29 00:10 UTC

**Comment by joevandyk** [comment] 2016-03-29 04:25
What if instead of using `container[:thing]`, you do `container.fetch(:thing)`? That would raise a better error if you were to use a hash for the container.

**Comment by timriley** [comment] 2016-03-29 04:32
@joevandyk That would work if a hash was the only kind of container we're working with, but I want to keep the integration with the container as slim as possible, i.e. just `#[]`. In any case, Dry::Container doesn't support `#fetch`, and `#fetch` feels very Hash-specific anyway.

If you really wanted to use a hash as a container, you could do something like this:

``` ruby
container = Hash.new { |_hash, key| raise ArgumentError, "+#{key}+ is not registered" }
container[:exists] = "hi"

container[:exists]
# => "hi"

container[:does_not_exist]
# => ArgumentError: +does_not_exist+ is not registered
```
